# Generated by Django 2.2 on 2019-04-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecuserauth', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
