# Generated by Django 2.2 on 2019-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
