# Generated by Django 2.2 on 2019-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecproduct', '0002_auto_20190428_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'permissions': (('onlyread', 'onlyread'), ('readwrite', 'readwrite'))},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
